
// This file has been generated by the GUI designer. Do not modify.
namespace FileSearch
{
	public partial class anDialog
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label4;
		private global::Gtk.Label label3;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Label label10;
		private global::Gtk.Label label9;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeview1;
		private global::Gtk.VBox vboxDopalnitelni;
		private global::Gtk.Label label7;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label labelTrdO;
		private global::Gtk.Label labelTrdV;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.Label labelMtrO;
		private global::Gtk.Label labelMtrV;
		private global::Gtk.VSeparator vseparator2;
		private global::Gtk.Label labelMhnO;
		private global::Gtk.Label labelMhnV;
		private global::Gtk.VSeparator vseparator3;
		private global::Gtk.Label labelUslO;
		private global::Gtk.Label labelUslV;
		private global::Gtk.Label labelDopV;
		private global::Gtk.Label labelDopO;
		private global::Gtk.VBox vboxDopalnitelni1;
		private global::Gtk.Label label8;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Label labelPrekiO;
		private global::Gtk.Label labelPrekiV;
		private global::Gtk.VSeparator vseparator4;
		private global::Gtk.Label labelPDO;
		private global::Gtk.Label labelPDV;
		private global::Gtk.VSeparator vseparator5;
		private global::Gtk.Label labelPeO;
		private global::Gtk.Label labelPeV;
		private global::Gtk.Label labelSumV;
		private global::Gtk.Label labelSumO;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FileSearch.anDialog
			this.Name = "FileSearch.anDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child FileSearch.anDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 3;
			this.vbox2.BorderWidth = ((uint)(3));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 3;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Описание:");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.hbox1.Add (this.label2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label2]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("label4");
			this.hbox1.Add (this.label4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label4]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Дименсия:");
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 3;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Основание:");
			this.hbox2.Add (this.label5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label5]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("label6");
			this.hbox2.Add (this.label6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label6]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Примерна сметка");
			this.hbox2.Add (this.label10);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label10]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Файл:");
			this.hbox2.Add (this.label9);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label9]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add (this.treeview1);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w13.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vboxDopalnitelni = new global::Gtk.VBox ();
			this.vboxDopalnitelni.Name = "vboxDopalnitelni";
			this.vboxDopalnitelni.Spacing = 3;
			// Container child vboxDopalnitelni.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Допълнителни разходи:</b>");
			this.label7.UseMarkup = true;
			this.vboxDopalnitelni.Add (this.label7);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxDopalnitelni [this.label7]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vboxDopalnitelni.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelTrdO = new global::Gtk.Label ();
			this.labelTrdO.Name = "labelTrdO";
			this.labelTrdO.LabelProp = global::Mono.Unix.Catalog.GetString ("Труд [80 %]:");
			this.hbox4.Add (this.labelTrdO);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelTrdO]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelTrdV = new global::Gtk.Label ();
			this.labelTrdV.Name = "labelTrdV";
			this.labelTrdV.LabelProp = global::Mono.Unix.Catalog.GetString ("8.45");
			this.hbox4.Add (this.labelTrdV);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelTrdV]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox4.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vseparator1]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelMtrO = new global::Gtk.Label ();
			this.labelMtrO.Name = "labelMtrO";
			this.labelMtrO.LabelProp = global::Mono.Unix.Catalog.GetString ("Материали [20 %]:");
			this.hbox4.Add (this.labelMtrO);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelMtrO]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelMtrV = new global::Gtk.Label ();
			this.labelMtrV.Name = "labelMtrV";
			this.labelMtrV.LabelProp = global::Mono.Unix.Catalog.GetString ("24.34");
			this.hbox4.Add (this.labelMtrV);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelMtrV]));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.hbox4.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vseparator2]));
			w20.Position = 5;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelMhnO = new global::Gtk.Label ();
			this.labelMhnO.Name = "labelMhnO";
			this.labelMhnO.LabelProp = global::Mono.Unix.Catalog.GetString ("Механизация [20 %]:");
			this.hbox4.Add (this.labelMhnO);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelMhnO]));
			w21.Position = 6;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelMhnV = new global::Gtk.Label ();
			this.labelMhnV.Name = "labelMhnV";
			this.labelMhnV.LabelProp = global::Mono.Unix.Catalog.GetString ("1.55");
			this.hbox4.Add (this.labelMhnV);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelMhnV]));
			w22.Position = 7;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator ();
			this.vseparator3.Name = "vseparator3";
			this.hbox4.Add (this.vseparator3);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vseparator3]));
			w23.Position = 8;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelUslO = new global::Gtk.Label ();
			this.labelUslO.Name = "labelUslO";
			this.labelUslO.LabelProp = global::Mono.Unix.Catalog.GetString ("Услуги [0 %]:");
			this.hbox4.Add (this.labelUslO);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelUslO]));
			w24.Position = 9;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelUslV = new global::Gtk.Label ();
			this.labelUslV.Name = "labelUslV";
			this.labelUslV.LabelProp = global::Mono.Unix.Catalog.GetString ("0.00");
			this.hbox4.Add (this.labelUslV);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelUslV]));
			w25.Position = 10;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelDopV = new global::Gtk.Label ();
			this.labelDopV.Name = "labelDopV";
			this.labelDopV.LabelProp = global::Mono.Unix.Catalog.GetString ("33.25");
			this.hbox4.Add (this.labelDopV);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelDopV]));
			w26.PackType = ((global::Gtk.PackType)(1));
			w26.Position = 12;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelDopO = new global::Gtk.Label ();
			this.labelDopO.Name = "labelDopO";
			this.labelDopO.LabelProp = global::Mono.Unix.Catalog.GetString ("Допълнителни:");
			this.hbox4.Add (this.labelDopO);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelDopO]));
			w27.PackType = ((global::Gtk.PackType)(1));
			w27.Position = 13;
			w27.Expand = false;
			w27.Fill = false;
			this.vboxDopalnitelni.Add (this.hbox4);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vboxDopalnitelni [this.hbox4]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox2.Add (this.vboxDopalnitelni);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vboxDopalnitelni]));
			w29.Position = 3;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vboxDopalnitelni1 = new global::Gtk.VBox ();
			this.vboxDopalnitelni1.Name = "vboxDopalnitelni1";
			this.vboxDopalnitelni1.Spacing = 3;
			// Container child vboxDopalnitelni1.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Сумарни стойности:</b>");
			this.label8.UseMarkup = true;
			this.vboxDopalnitelni1.Add (this.label8);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vboxDopalnitelni1 [this.label8]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vboxDopalnitelni1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labelPrekiO = new global::Gtk.Label ();
			this.labelPrekiO.Name = "labelPrekiO";
			this.labelPrekiO.LabelProp = global::Mono.Unix.Catalog.GetString ("Преки разходи:");
			this.hbox7.Add (this.labelPrekiO);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.labelPrekiO]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labelPrekiV = new global::Gtk.Label ();
			this.labelPrekiV.Name = "labelPrekiV";
			this.labelPrekiV.LabelProp = global::Mono.Unix.Catalog.GetString ("20.32");
			this.hbox7.Add (this.labelPrekiV);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.labelPrekiV]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vseparator4 = new global::Gtk.VSeparator ();
			this.vseparator4.Name = "vseparator4";
			this.hbox7.Add (this.vseparator4);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vseparator4]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labelPDO = new global::Gtk.Label ();
			this.labelPDO.Name = "labelPDO";
			this.labelPDO.LabelProp = global::Mono.Unix.Catalog.GetString ("Преки и допълнителни:");
			this.hbox7.Add (this.labelPDO);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.labelPDO]));
			w34.Position = 3;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labelPDV = new global::Gtk.Label ();
			this.labelPDV.Name = "labelPDV";
			this.labelPDV.LabelProp = global::Mono.Unix.Catalog.GetString ("58.12");
			this.hbox7.Add (this.labelPDV);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.labelPDV]));
			w35.Position = 4;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vseparator5 = new global::Gtk.VSeparator ();
			this.vseparator5.Name = "vseparator5";
			this.hbox7.Add (this.vseparator5);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vseparator5]));
			w36.Position = 5;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labelPeO = new global::Gtk.Label ();
			this.labelPeO.Name = "labelPeO";
			this.labelPeO.LabelProp = global::Mono.Unix.Catalog.GetString ("Печалба [10 %]:");
			this.hbox7.Add (this.labelPeO);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.labelPeO]));
			w37.Position = 6;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labelPeV = new global::Gtk.Label ();
			this.labelPeV.Name = "labelPeV";
			this.labelPeV.LabelProp = global::Mono.Unix.Catalog.GetString ("5.20");
			this.hbox7.Add (this.labelPeV);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.labelPeV]));
			w38.Position = 7;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labelSumV = new global::Gtk.Label ();
			this.labelSumV.Name = "labelSumV";
			this.labelSumV.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>62.10</b>");
			this.labelSumV.UseMarkup = true;
			this.hbox7.Add (this.labelSumV);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.labelSumV]));
			w39.PackType = ((global::Gtk.PackType)(1));
			w39.Position = 9;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labelSumO = new global::Gtk.Label ();
			this.labelSumO.Name = "labelSumO";
			this.labelSumO.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Общо:</b>");
			this.labelSumO.UseMarkup = true;
			this.hbox7.Add (this.labelSumO);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.labelSumO]));
			w40.PackType = ((global::Gtk.PackType)(1));
			w40.Position = 10;
			w40.Expand = false;
			w40.Fill = false;
			this.vboxDopalnitelni1.Add (this.hbox7);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vboxDopalnitelni1 [this.hbox7]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			this.vbox2.Add (this.vboxDopalnitelni1);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vboxDopalnitelni1]));
			w42.Position = 4;
			w42.Expand = false;
			w42.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w43.Position = 0;
			// Internal child FileSearch.anDialog.ActionArea
			global::Gtk.HButtonBox w44 = this.ActionArea;
			w44.Name = "dialog1_ActionArea";
			w44.Spacing = 10;
			w44.BorderWidth = ((uint)(5));
			w44.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w45 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w44 [this.buttonCancel]));
			w45.Expand = false;
			w45.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w46 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w44 [this.buttonOk]));
			w46.Position = 1;
			w46.Expand = false;
			w46.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 820;
			this.DefaultHeight = 456;
			this.Show ();
		}
	}
}
