
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Label label15;
	private global::Gtk.HSeparator hseparator6;
	private global::Gtk.Label label18;
	private global::Gtk.Label label19;
	private global::Gtk.HSeparator hseparator7;
	private global::Gtk.HBox hbox11;
	private global::Gtk.Label label21;
	private global::Gtk.FileChooserButton FirstDirChoise;
	private global::Gtk.Button btnFirstDirOpen;
	private global::Gtk.Label label20;
	private global::Gtk.HSeparator hseparator8;
	private global::Gtk.HBox hbox13;
	private global::Gtk.Label label22;
	private global::Gtk.Button btnFristMarkAll;
	private global::Gtk.Button btnFristTableRefresh;
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	private global::Gtk.NodeView viewFirstFiles;
	private global::Gtk.HBox hbox12;
	private global::Gtk.Button btnSetSamples;
	private global::Gtk.Button btnGoToMainScreen;
	private global::Gtk.Label label1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label label6;
	private global::Gtk.Entry entrySearch;
	private global::Gtk.Button btnSearch;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.NodeView viewSearch;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Button btnGoToRes;
	private global::Gtk.VSeparator vseparator1;
	private global::Gtk.Button btnUpdate;
	private global::Gtk.Button btnSettings;
	private global::Gtk.Button btnCopyAn;
	private global::Gtk.Button btnCopyRow;
	private global::Gtk.Label label2;
	private global::Gtk.VBox vbox7;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Button btnBackInSearch;
	private global::Gtk.Label label16;
	private global::Gtk.Entry entrySearchResources;
	private global::Gtk.Label label17;
	private global::Gtk.ComboBox comboboxSearchInDB;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.NodeView viewResources;
	private global::Gtk.HBox hbox10;
	private global::Gtk.Button btnCopyResRow;
	private global::Gtk.Label label3;
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Button btnFFBack;
	private global::Gtk.Button btnFFUpdate;
	private global::Gtk.Button btnFFContainFolder;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.NodeView viewFiles;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button btnFFMark;
	private global::Gtk.Label label4;
	private global::Gtk.VBox vbox4;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Button btnBackSettings;
	private global::Gtk.Button btnRunAppDataSettings;
	private global::Gtk.HSeparator hseparator1;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Label label11;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label label12;
	private global::Gtk.RadioButton radioSMAnd;
	private global::Gtk.RadioButton radioSMOr;
	private global::Gtk.RadioButton radioSMOff;
	private global::Gtk.HSeparator hseparator3;
	private global::Gtk.Label label7;
	private global::Gtk.Table table1;
	private global::Gtk.CheckButton checkColAn;
	private global::Gtk.CheckButton checkColDop;
	private global::Gtk.CheckButton checkColFile;
	private global::Gtk.CheckButton checkColMhn;
	private global::Gtk.CheckButton checkColMka;
	private global::Gtk.CheckButton checkColMtr;
	private global::Gtk.CheckButton checkColNvr;
	private global::Gtk.CheckButton checkColOpisanie;
	private global::Gtk.CheckButton checkColOsnovanie;
	private global::Gtk.CheckButton checkColPe4;
	private global::Gtk.CheckButton checkColPePr;
	private global::Gtk.CheckButton checkColSum;
	private global::Gtk.CheckButton checkColTrd;
	private global::Gtk.CheckButton checkColUsl;
	private global::Gtk.Label label10;
	private global::Gtk.Label label8;
	private global::Gtk.Label label9;
	private global::Gtk.HSeparator hseparator4;
	private global::Gtk.Label label13;
	private global::Gtk.HBox hbox8;
	private global::Gtk.CheckButton checkbuttonFixedColumn;
	private global::Gtk.HSeparator hseparator5;
	private global::Gtk.VBox vbox6;
	private global::Gtk.Label label5;
	private global::Gtk.HBox hbox6;
	private global::Gtk.FileChooserButton DirChoiseSettings;
	private global::Gtk.Button btnRunBaseDirSettings;
	private global::Gtk.HSeparator hseparator2;
	private global::Gtk.Label label14;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 3;
		this.vbox2.BorderWidth = ((uint)(3));
		// Container child vbox2.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.Xalign = 0F;
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\"large\" foreground=\"#5f5f5f\"><b>Стартиране на PE File Search за първи " +
			"път</b></span>");
		this.label15.UseMarkup = true;
		this.vbox2.Add (this.label15);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label15]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator6 = new global::Gtk.HSeparator ();
		this.hseparator6.Name = "hseparator6";
		this.vbox2.Add (this.hseparator6);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator6]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label18 = new global::Gtk.Label ();
		this.label18.Name = "label18";
		this.label18.Xalign = 0F;
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString (@"PE File Search служи за създаване и използване на база данни от съществуващи сметки направени с Projet Estimator.  С програмата ще
можете да търсите позиции, работници, материали или механизация, които вече сте използвали.

За целта трябва се избере директория от, която PE File Search да чете файловете и разбира се в нея да бъдат поставени такива."
		);
		this.vbox2.Add (this.label18);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label18]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label19 = new global::Gtk.Label ();
		this.label19.Name = "label19";
		this.label19.Xalign = 0F;
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("\n<span size=\"large\" foreground=\"#5f5f5f\"><b>1. Избор на базова директория</b></sp" +
			"an>");
		this.label19.UseMarkup = true;
		this.vbox2.Add (this.label19);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label19]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator7 = new global::Gtk.HSeparator ();
		this.hseparator7.Name = "hseparator7";
		this.vbox2.Add (this.hseparator7);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator7]));
		w5.Position = 4;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 3;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label21 = new global::Gtk.Label ();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Избор на директория: ");
		this.hbox11.Add (this.label21);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label21]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.FirstDirChoise = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Изберете базова директория"), ((global::Gtk.FileChooserAction)(2)));
		this.FirstDirChoise.Name = "FirstDirChoise";
		this.FirstDirChoise.ShowHidden = true;
		this.hbox11.Add (this.FirstDirChoise);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.FirstDirChoise]));
		w7.Position = 1;
		// Container child hbox11.Gtk.Box+BoxChild
		this.btnFirstDirOpen = new global::Gtk.Button ();
		this.btnFirstDirOpen.Sensitive = false;
		this.btnFirstDirOpen.CanFocus = true;
		this.btnFirstDirOpen.Name = "btnFirstDirOpen";
		this.btnFirstDirOpen.UseUnderline = true;
		// Container child btnFirstDirOpen.Gtk.Container+ContainerChild
		global::Gtk.Alignment w8 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w9 = new global::Gtk.HBox ();
		w9.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w10 = new global::Gtk.Image ();
		w10.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-directory", global::Gtk.IconSize.SmallToolbar);
		w9.Add (w10);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w12 = new global::Gtk.Label ();
		w12.LabelProp = global::Mono.Unix.Catalog.GetString (" Отвори избраната директория");
		w12.UseUnderline = true;
		w9.Add (w12);
		w8.Add (w9);
		this.btnFirstDirOpen.Add (w8);
		this.hbox11.Add (this.btnFirstDirOpen);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.btnFirstDirOpen]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox2.Add (this.hbox11);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox11]));
		w17.Position = 5;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label20 = new global::Gtk.Label ();
		this.label20.Name = "label20";
		this.label20.Xalign = 0F;
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("\n<span size=\"large\" foreground=\"#5f5f5f\"><b>2. Преглед и избор на сметки</b></spa" +
			"n>");
		this.label20.UseMarkup = true;
		this.vbox2.Add (this.label20);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label20]));
		w18.Position = 6;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator8 = new global::Gtk.HSeparator ();
		this.hseparator8.Name = "hseparator8";
		this.vbox2.Add (this.hseparator8);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator8]));
		w19.Position = 7;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 3;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label22 = new global::Gtk.Label ();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Списък с файлове от избраната директория:");
		this.hbox13.Add (this.label22);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label22]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.btnFristMarkAll = new global::Gtk.Button ();
		this.btnFristMarkAll.Sensitive = false;
		this.btnFristMarkAll.CanFocus = true;
		this.btnFristMarkAll.Name = "btnFristMarkAll";
		this.btnFristMarkAll.UseUnderline = true;
		// Container child btnFristMarkAll.Gtk.Container+ContainerChild
		global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w22 = new global::Gtk.HBox ();
		w22.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w23 = new global::Gtk.Image ();
		w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dnd-multiple", global::Gtk.IconSize.SmallToolbar);
		w22.Add (w23);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w25 = new global::Gtk.Label ();
		w25.LabelProp = global::Mono.Unix.Catalog.GetString (" Маркирай / Размаркирай всички");
		w25.UseUnderline = true;
		w22.Add (w25);
		w21.Add (w22);
		this.btnFristMarkAll.Add (w21);
		this.hbox13.Add (this.btnFristMarkAll);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.btnFristMarkAll]));
		w29.PackType = ((global::Gtk.PackType)(1));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.btnFristTableRefresh = new global::Gtk.Button ();
		this.btnFristTableRefresh.Sensitive = false;
		this.btnFristTableRefresh.CanFocus = true;
		this.btnFristTableRefresh.Name = "btnFristTableRefresh";
		this.btnFristTableRefresh.UseUnderline = true;
		// Container child btnFristTableRefresh.Gtk.Container+ContainerChild
		global::Gtk.Alignment w30 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w31 = new global::Gtk.HBox ();
		w31.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w32 = new global::Gtk.Image ();
		w32.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.SmallToolbar);
		w31.Add (w32);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w34 = new global::Gtk.Label ();
		w34.LabelProp = global::Mono.Unix.Catalog.GetString (" Презареди файловете");
		w34.UseUnderline = true;
		w31.Add (w34);
		w30.Add (w31);
		this.btnFristTableRefresh.Add (w30);
		this.hbox13.Add (this.btnFristTableRefresh);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.btnFristTableRefresh]));
		w38.PackType = ((global::Gtk.PackType)(1));
		w38.Position = 3;
		w38.Expand = false;
		w38.Fill = false;
		this.vbox2.Add (this.hbox13);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox13]));
		w39.Position = 8;
		w39.Expand = false;
		w39.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.viewFirstFiles = new global::Gtk.NodeView ();
		this.viewFirstFiles.Sensitive = false;
		this.viewFirstFiles.CanFocus = true;
		this.viewFirstFiles.Name = "viewFirstFiles";
		this.GtkScrolledWindow3.Add (this.viewFirstFiles);
		this.vbox2.Add (this.GtkScrolledWindow3);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow3]));
		w41.Position = 9;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 3;
		// Container child hbox12.Gtk.Box+BoxChild
		this.btnSetSamples = new global::Gtk.Button ();
		this.btnSetSamples.Sensitive = false;
		this.btnSetSamples.CanFocus = true;
		this.btnSetSamples.Name = "btnSetSamples";
		this.btnSetSamples.UseUnderline = true;
		// Container child btnSetSamples.Gtk.Container+ContainerChild
		global::Gtk.Alignment w42 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w43 = new global::Gtk.HBox ();
		w43.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w44 = new global::Gtk.Image ();
		w44.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-convert", global::Gtk.IconSize.SmallToolbar);
		w43.Add (w44);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w46 = new global::Gtk.Label ();
		w46.LabelProp = global::Mono.Unix.Catalog.GetString (" Постави примени сметки");
		w46.UseUnderline = true;
		w43.Add (w46);
		w42.Add (w43);
		this.btnSetSamples.Add (w42);
		this.hbox12.Add (this.btnSetSamples);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.btnSetSamples]));
		w50.Position = 0;
		w50.Expand = false;
		w50.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.btnGoToMainScreen = new global::Gtk.Button ();
		this.btnGoToMainScreen.Sensitive = false;
		this.btnGoToMainScreen.CanFocus = true;
		this.btnGoToMainScreen.Name = "btnGoToMainScreen";
		this.btnGoToMainScreen.UseUnderline = true;
		// Container child btnGoToMainScreen.Gtk.Container+ContainerChild
		global::Gtk.Alignment w51 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w52 = new global::Gtk.HBox ();
		w52.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w53 = new global::Gtk.Image ();
		w53.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-floppy", global::Gtk.IconSize.SmallToolbar);
		w52.Add (w53);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w55 = new global::Gtk.Label ();
		w55.LabelProp = global::Mono.Unix.Catalog.GetString (" Запамети тези настройки и продължи");
		w55.UseUnderline = true;
		w52.Add (w55);
		w51.Add (w52);
		this.btnGoToMainScreen.Add (w51);
		this.hbox12.Add (this.btnGoToMainScreen);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.btnGoToMainScreen]));
		w59.PackType = ((global::Gtk.PackType)(1));
		w59.Position = 3;
		w59.Expand = false;
		w59.Fill = false;
		this.vbox2.Add (this.hbox12);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox12]));
		w60.PackType = ((global::Gtk.PackType)(1));
		w60.Position = 11;
		w60.Expand = false;
		w60.Fill = false;
		this.notebook1.Add (this.vbox2);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("FirstTimeRun");
		this.notebook1.SetTabLabel (this.vbox2, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 3;
		this.vbox1.BorderWidth = ((uint)(3));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 3;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Търси:</b> ");
		this.label6.UseMarkup = true;
		this.hbox1.Add (this.label6);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label6]));
		w62.Position = 0;
		w62.Expand = false;
		w62.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entrySearch = new global::Gtk.Entry ();
		this.entrySearch.CanFocus = true;
		this.entrySearch.Name = "entrySearch";
		this.entrySearch.Text = global::Mono.Unix.Catalog.GetString ("Зареждане на основните бази данни ...");
		this.entrySearch.IsEditable = true;
		this.entrySearch.InvisibleChar = '●';
		this.hbox1.Add (this.entrySearch);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entrySearch]));
		w63.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnSearch = new global::Gtk.Button ();
		this.btnSearch.CanFocus = true;
		this.btnSearch.Name = "btnSearch";
		this.btnSearch.UseUnderline = true;
		// Container child btnSearch.Gtk.Container+ContainerChild
		global::Gtk.Alignment w64 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w65 = new global::Gtk.HBox ();
		w65.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w66 = new global::Gtk.Image ();
		w66.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.SmallToolbar);
		w65.Add (w66);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w68 = new global::Gtk.Label ();
		w68.LabelProp = global::Mono.Unix.Catalog.GetString (" Търси");
		w68.UseUnderline = true;
		w65.Add (w68);
		w64.Add (w65);
		this.btnSearch.Add (w64);
		this.hbox1.Add (this.btnSearch);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnSearch]));
		w72.Position = 2;
		w72.Expand = false;
		w72.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w73.Position = 0;
		w73.Expand = false;
		w73.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.viewSearch = new global::Gtk.NodeView ();
		this.viewSearch.CanFocus = true;
		this.viewSearch.Name = "viewSearch";
		this.GtkScrolledWindow1.Add (this.viewSearch);
		this.vbox1.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow1]));
		w75.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 3;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnGoToRes = new global::Gtk.Button ();
		this.btnGoToRes.TooltipMarkup = "Търсене за цени на материали или часови ставки и машиносмени";
		this.btnGoToRes.CanFocus = true;
		this.btnGoToRes.Name = "btnGoToRes";
		this.btnGoToRes.UseUnderline = true;
		// Container child btnGoToRes.Gtk.Container+ContainerChild
		global::Gtk.Alignment w76 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w77 = new global::Gtk.HBox ();
		w77.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w78 = new global::Gtk.Image ();
		w78.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.SmallToolbar);
		w77.Add (w78);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w80 = new global::Gtk.Label ();
		w80.LabelProp = global::Mono.Unix.Catalog.GetString (" Търси в цени на материали");
		w80.UseUnderline = true;
		w77.Add (w80);
		w76.Add (w77);
		this.btnGoToRes.Add (w76);
		this.hbox4.Add (this.btnGoToRes);
		global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnGoToRes]));
		w84.Position = 0;
		w84.Expand = false;
		w84.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator ();
		this.vseparator1.Name = "vseparator1";
		this.hbox4.Add (this.vseparator1);
		global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vseparator1]));
		w85.Position = 1;
		w85.Expand = false;
		w85.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnUpdate = new global::Gtk.Button ();
		this.btnUpdate.TooltipMarkup = "Актуализиране на базата данни от файлове";
		this.btnUpdate.CanFocus = true;
		this.btnUpdate.Name = "btnUpdate";
		this.btnUpdate.UseUnderline = true;
		// Container child btnUpdate.Gtk.Container+ContainerChild
		global::Gtk.Alignment w86 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w87 = new global::Gtk.HBox ();
		w87.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w88 = new global::Gtk.Image ();
		w88.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.SmallToolbar);
		w87.Add (w88);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w90 = new global::Gtk.Label ();
		w90.LabelProp = global::Mono.Unix.Catalog.GetString (" Актуализиране");
		w90.UseUnderline = true;
		w87.Add (w90);
		w86.Add (w87);
		this.btnUpdate.Add (w86);
		this.hbox4.Add (this.btnUpdate);
		global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnUpdate]));
		w94.Position = 2;
		w94.Expand = false;
		w94.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnSettings = new global::Gtk.Button ();
		this.btnSettings.CanFocus = true;
		this.btnSettings.Name = "btnSettings";
		this.btnSettings.UseUnderline = true;
		// Container child btnSettings.Gtk.Container+ContainerChild
		global::Gtk.Alignment w95 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w96 = new global::Gtk.HBox ();
		w96.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w97 = new global::Gtk.Image ();
		w97.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-properties", global::Gtk.IconSize.SmallToolbar);
		w96.Add (w97);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w99 = new global::Gtk.Label ();
		w99.LabelProp = global::Mono.Unix.Catalog.GetString (" Настройки");
		w99.UseUnderline = true;
		w96.Add (w99);
		w95.Add (w96);
		this.btnSettings.Add (w95);
		this.hbox4.Add (this.btnSettings);
		global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnSettings]));
		w103.Position = 3;
		w103.Expand = false;
		w103.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnCopyAn = new global::Gtk.Button ();
		this.btnCopyAn.TooltipMarkup = "Копиране само на анализ в набрана позиция на Project Estimator";
		this.btnCopyAn.CanFocus = true;
		this.btnCopyAn.Name = "btnCopyAn";
		this.btnCopyAn.UseUnderline = true;
		// Container child btnCopyAn.Gtk.Container+ContainerChild
		global::Gtk.Alignment w104 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w105 = new global::Gtk.HBox ();
		w105.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w106 = new global::Gtk.Image ();
		w106.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-copy", global::Gtk.IconSize.SmallToolbar);
		w105.Add (w106);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w108 = new global::Gtk.Label ();
		w108.LabelProp = global::Mono.Unix.Catalog.GetString (" Копирай анализ");
		w108.UseUnderline = true;
		w105.Add (w108);
		w104.Add (w105);
		this.btnCopyAn.Add (w104);
		this.hbox4.Add (this.btnCopyAn);
		global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnCopyAn]));
		w112.PackType = ((global::Gtk.PackType)(1));
		w112.Position = 7;
		w112.Expand = false;
		w112.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnCopyRow = new global::Gtk.Button ();
		this.btnCopyRow.TooltipMarkup = "Копиране на целия ред в Project Estimator";
		this.btnCopyRow.CanFocus = true;
		this.btnCopyRow.Name = "btnCopyRow";
		this.btnCopyRow.UseUnderline = true;
		// Container child btnCopyRow.Gtk.Container+ContainerChild
		global::Gtk.Alignment w113 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w114 = new global::Gtk.HBox ();
		w114.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w115 = new global::Gtk.Image ();
		w115.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-copy", global::Gtk.IconSize.SmallToolbar);
		w114.Add (w115);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w117 = new global::Gtk.Label ();
		w117.LabelProp = global::Mono.Unix.Catalog.GetString (" Позиция");
		w117.UseUnderline = true;
		w114.Add (w117);
		w113.Add (w114);
		this.btnCopyRow.Add (w113);
		this.hbox4.Add (this.btnCopyRow);
		global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnCopyRow]));
		w121.PackType = ((global::Gtk.PackType)(1));
		w121.Position = 8;
		w121.Expand = false;
		w121.Fill = false;
		this.vbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
		w122.Position = 2;
		w122.Expand = false;
		w122.Fill = false;
		this.notebook1.Add (this.vbox1);
		global::Gtk.Notebook.NotebookChild w123 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox1]));
		w123.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Search");
		this.notebook1.SetTabLabel (this.vbox1, this.label2);
		this.label2.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 3;
		this.vbox7.BorderWidth = ((uint)(3));
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 3;
		// Container child hbox9.Gtk.Box+BoxChild
		this.btnBackInSearch = new global::Gtk.Button ();
		this.btnBackInSearch.CanFocus = true;
		this.btnBackInSearch.Name = "btnBackInSearch";
		this.btnBackInSearch.UseUnderline = true;
		// Container child btnBackInSearch.Gtk.Container+ContainerChild
		global::Gtk.Alignment w124 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w125 = new global::Gtk.HBox ();
		w125.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w126 = new global::Gtk.Image ();
		w126.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-first", global::Gtk.IconSize.SmallToolbar);
		w125.Add (w126);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w128 = new global::Gtk.Label ();
		w128.LabelProp = global::Mono.Unix.Catalog.GetString (" Назад");
		w128.UseUnderline = true;
		w125.Add (w128);
		w124.Add (w125);
		this.btnBackInSearch.Add (w124);
		this.hbox9.Add (this.btnBackInSearch);
		global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.btnBackInSearch]));
		w132.Position = 0;
		w132.Expand = false;
		w132.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("     <b>Търси:</b> ");
		this.label16.UseMarkup = true;
		this.hbox9.Add (this.label16);
		global::Gtk.Box.BoxChild w133 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label16]));
		w133.Position = 1;
		w133.Expand = false;
		w133.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.entrySearchResources = new global::Gtk.Entry ();
		this.entrySearchResources.CanFocus = true;
		this.entrySearchResources.Name = "entrySearchResources";
		this.entrySearchResources.IsEditable = true;
		this.entrySearchResources.InvisibleChar = '●';
		this.hbox9.Add (this.entrySearchResources);
		global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.entrySearchResources]));
		w134.Position = 2;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label17 = new global::Gtk.Label ();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString (" в ");
		this.hbox9.Add (this.label17);
		global::Gtk.Box.BoxChild w135 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label17]));
		w135.Position = 3;
		w135.Expand = false;
		w135.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.comboboxSearchInDB = global::Gtk.ComboBox.NewText ();
		this.comboboxSearchInDB.Name = "comboboxSearchInDB";
		this.hbox9.Add (this.comboboxSearchInDB);
		global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.comboboxSearchInDB]));
		w136.Position = 4;
		w136.Expand = false;
		w136.Fill = false;
		this.vbox7.Add (this.hbox9);
		global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox9]));
		w137.Position = 0;
		w137.Expand = false;
		w137.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.viewResources = new global::Gtk.NodeView ();
		this.viewResources.CanFocus = true;
		this.viewResources.Name = "viewResources";
		this.GtkScrolledWindow2.Add (this.viewResources);
		this.vbox7.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.GtkScrolledWindow2]));
		w139.Position = 1;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 3;
		// Container child hbox10.Gtk.Box+BoxChild
		this.btnCopyResRow = new global::Gtk.Button ();
		this.btnCopyResRow.CanFocus = true;
		this.btnCopyResRow.Name = "btnCopyResRow";
		this.btnCopyResRow.UseUnderline = true;
		// Container child btnCopyResRow.Gtk.Container+ContainerChild
		global::Gtk.Alignment w140 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w141 = new global::Gtk.HBox ();
		w141.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w142 = new global::Gtk.Image ();
		w142.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-copy", global::Gtk.IconSize.SmallToolbar);
		w141.Add (w142);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w144 = new global::Gtk.Label ();
		w144.LabelProp = global::Mono.Unix.Catalog.GetString (" Копиране на ресурс");
		w144.UseUnderline = true;
		w141.Add (w144);
		w140.Add (w141);
		this.btnCopyResRow.Add (w140);
		this.hbox10.Add (this.btnCopyResRow);
		global::Gtk.Box.BoxChild w148 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.btnCopyResRow]));
		w148.PackType = ((global::Gtk.PackType)(1));
		w148.Position = 2;
		w148.Expand = false;
		w148.Fill = false;
		this.vbox7.Add (this.hbox10);
		global::Gtk.Box.BoxChild w149 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox10]));
		w149.Position = 2;
		w149.Expand = false;
		w149.Fill = false;
		this.notebook1.Add (this.vbox7);
		global::Gtk.Notebook.NotebookChild w150 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox7]));
		w150.Position = 2;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Resources");
		this.notebook1.SetTabLabel (this.vbox7, this.label3);
		this.label3.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 3;
		this.vbox3.BorderWidth = ((uint)(3));
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 3;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnFFBack = new global::Gtk.Button ();
		this.btnFFBack.CanFocus = true;
		this.btnFFBack.Name = "btnFFBack";
		this.btnFFBack.UseUnderline = true;
		// Container child btnFFBack.Gtk.Container+ContainerChild
		global::Gtk.Alignment w151 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w152 = new global::Gtk.HBox ();
		w152.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w153 = new global::Gtk.Image ();
		w153.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-first", global::Gtk.IconSize.SmallToolbar);
		w152.Add (w153);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w155 = new global::Gtk.Label ();
		w155.LabelProp = global::Mono.Unix.Catalog.GetString (" Назад");
		w155.UseUnderline = true;
		w152.Add (w155);
		w151.Add (w152);
		this.btnFFBack.Add (w151);
		this.hbox3.Add (this.btnFFBack);
		global::Gtk.Box.BoxChild w159 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnFFBack]));
		w159.Position = 0;
		w159.Expand = false;
		w159.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnFFUpdate = new global::Gtk.Button ();
		this.btnFFUpdate.CanFocus = true;
		this.btnFFUpdate.Name = "btnFFUpdate";
		this.btnFFUpdate.UseUnderline = true;
		// Container child btnFFUpdate.Gtk.Container+ContainerChild
		global::Gtk.Alignment w160 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w161 = new global::Gtk.HBox ();
		w161.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w162 = new global::Gtk.Image ();
		w162.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.SmallToolbar);
		w161.Add (w162);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w164 = new global::Gtk.Label ();
		w161.Add (w164);
		w160.Add (w161);
		this.btnFFUpdate.Add (w160);
		this.hbox3.Add (this.btnFFUpdate);
		global::Gtk.Box.BoxChild w168 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnFFUpdate]));
		w168.PackType = ((global::Gtk.PackType)(1));
		w168.Position = 2;
		w168.Expand = false;
		w168.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnFFContainFolder = new global::Gtk.Button ();
		this.btnFFContainFolder.CanFocus = true;
		this.btnFFContainFolder.Name = "btnFFContainFolder";
		this.btnFFContainFolder.UseUnderline = true;
		// Container child btnFFContainFolder.Gtk.Container+ContainerChild
		global::Gtk.Alignment w169 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w170 = new global::Gtk.HBox ();
		w170.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w171 = new global::Gtk.Image ();
		w171.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-directory", global::Gtk.IconSize.SmallToolbar);
		w170.Add (w171);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w173 = new global::Gtk.Label ();
		w173.LabelProp = global::Mono.Unix.Catalog.GetString (" Базова директория");
		w173.UseUnderline = true;
		w170.Add (w173);
		w169.Add (w170);
		this.btnFFContainFolder.Add (w169);
		this.hbox3.Add (this.btnFFContainFolder);
		global::Gtk.Box.BoxChild w177 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnFFContainFolder]));
		w177.PackType = ((global::Gtk.PackType)(1));
		w177.Position = 3;
		w177.Expand = false;
		w177.Fill = false;
		this.vbox3.Add (this.hbox3);
		global::Gtk.Box.BoxChild w178 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
		w178.Position = 0;
		w178.Expand = false;
		w178.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.viewFiles = new global::Gtk.NodeView ();
		this.viewFiles.CanFocus = true;
		this.viewFiles.Name = "viewFiles";
		this.GtkScrolledWindow.Add (this.viewFiles);
		this.vbox3.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w180 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
		w180.Position = 1;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 3;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnFFMark = new global::Gtk.Button ();
		this.btnFFMark.CanFocus = true;
		this.btnFFMark.Name = "btnFFMark";
		this.btnFFMark.UseUnderline = true;
		// Container child btnFFMark.Gtk.Container+ContainerChild
		global::Gtk.Alignment w181 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w182 = new global::Gtk.HBox ();
		w182.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w183 = new global::Gtk.Image ();
		w183.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dnd-multiple", global::Gtk.IconSize.SmallToolbar);
		w182.Add (w183);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w185 = new global::Gtk.Label ();
		w185.LabelProp = global::Mono.Unix.Catalog.GetString (" Маркирай / Размаркирай всички");
		w185.UseUnderline = true;
		w182.Add (w185);
		w181.Add (w182);
		this.btnFFMark.Add (w181);
		this.hbox2.Add (this.btnFFMark);
		global::Gtk.Box.BoxChild w189 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnFFMark]));
		w189.Position = 0;
		w189.Expand = false;
		w189.Fill = false;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w190 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w190.Position = 2;
		w190.Expand = false;
		w190.Fill = false;
		this.notebook1.Add (this.vbox3);
		global::Gtk.Notebook.NotebookChild w191 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox3]));
		w191.Position = 3;
		// Notebook tab
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("FindFiles");
		this.notebook1.SetTabLabel (this.vbox3, this.label4);
		this.label4.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 3;
		this.vbox4.BorderWidth = ((uint)(3));
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 3;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnBackSettings = new global::Gtk.Button ();
		this.btnBackSettings.CanFocus = true;
		this.btnBackSettings.Name = "btnBackSettings";
		this.btnBackSettings.UseUnderline = true;
		// Container child btnBackSettings.Gtk.Container+ContainerChild
		global::Gtk.Alignment w192 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w193 = new global::Gtk.HBox ();
		w193.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w194 = new global::Gtk.Image ();
		w194.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-first", global::Gtk.IconSize.SmallToolbar);
		w193.Add (w194);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w196 = new global::Gtk.Label ();
		w196.LabelProp = global::Mono.Unix.Catalog.GetString (" Назад");
		w196.UseUnderline = true;
		w193.Add (w196);
		w192.Add (w193);
		this.btnBackSettings.Add (w192);
		this.hbox5.Add (this.btnBackSettings);
		global::Gtk.Box.BoxChild w200 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btnBackSettings]));
		w200.Position = 0;
		w200.Expand = false;
		w200.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnRunAppDataSettings = new global::Gtk.Button ();
		this.btnRunAppDataSettings.CanFocus = true;
		this.btnRunAppDataSettings.Name = "btnRunAppDataSettings";
		this.btnRunAppDataSettings.UseUnderline = true;
		// Container child btnRunAppDataSettings.Gtk.Container+ContainerChild
		global::Gtk.Alignment w201 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w202 = new global::Gtk.HBox ();
		w202.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w203 = new global::Gtk.Image ();
		w203.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-directory", global::Gtk.IconSize.SmallToolbar);
		w202.Add (w203);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w205 = new global::Gtk.Label ();
		w205.LabelProp = global::Mono.Unix.Catalog.GetString (" Директория с настройки");
		w205.UseUnderline = true;
		w202.Add (w205);
		w201.Add (w202);
		this.btnRunAppDataSettings.Add (w201);
		this.hbox5.Add (this.btnRunAppDataSettings);
		global::Gtk.Box.BoxChild w209 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btnRunAppDataSettings]));
		w209.PackType = ((global::Gtk.PackType)(1));
		w209.Position = 3;
		w209.Expand = false;
		w209.Fill = false;
		this.vbox4.Add (this.hbox5);
		global::Gtk.Box.BoxChild w210 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
		w210.Position = 0;
		w210.Expand = false;
		w210.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox4.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w211 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator1]));
		w211.Position = 1;
		w211.Expand = false;
		w211.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 3;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.Xalign = 0F;
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\"large\"><b>Tърсене</b></span>");
		this.label11.UseMarkup = true;
		this.vbox5.Add (this.label11);
		global::Gtk.Box.BoxChild w212 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label11]));
		w212.Position = 0;
		w212.Expand = false;
		w212.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 3;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Използване на ");
		this.hbox7.Add (this.label12);
		global::Gtk.Box.BoxChild w213 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label12]));
		w213.Position = 0;
		w213.Expand = false;
		w213.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.radioSMAnd = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("и"));
		this.radioSMAnd.WidthRequest = 50;
		this.radioSMAnd.CanFocus = true;
		this.radioSMAnd.Name = "radioSMAnd";
		this.radioSMAnd.DrawIndicator = true;
		this.radioSMAnd.UseUnderline = true;
		this.radioSMAnd.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox7.Add (this.radioSMAnd);
		global::Gtk.Box.BoxChild w214 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.radioSMAnd]));
		w214.Position = 1;
		w214.Expand = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.radioSMOr = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("или"));
		this.radioSMOr.WidthRequest = 50;
		this.radioSMOr.CanFocus = true;
		this.radioSMOr.Name = "radioSMOr";
		this.radioSMOr.DrawIndicator = true;
		this.radioSMOr.UseUnderline = true;
		this.radioSMOr.Group = this.radioSMAnd.Group;
		this.hbox7.Add (this.radioSMOr);
		global::Gtk.Box.BoxChild w215 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.radioSMOr]));
		w215.Position = 2;
		w215.Expand = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.radioSMOff = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("ключова фраза"));
		this.radioSMOff.WidthRequest = 140;
		this.radioSMOff.CanFocus = true;
		this.radioSMOff.Name = "radioSMOff";
		this.radioSMOff.DrawIndicator = true;
		this.radioSMOff.UseUnderline = true;
		this.radioSMOff.Group = this.radioSMAnd.Group;
		this.hbox7.Add (this.radioSMOff);
		global::Gtk.Box.BoxChild w216 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.radioSMOff]));
		w216.Position = 3;
		w216.Expand = false;
		this.vbox5.Add (this.hbox7);
		global::Gtk.Box.BoxChild w217 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox7]));
		w217.Position = 1;
		w217.Expand = false;
		w217.Fill = false;
		this.vbox4.Add (this.vbox5);
		global::Gtk.Box.BoxChild w218 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox5]));
		w218.Position = 2;
		w218.Expand = false;
		w218.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.Name = "hseparator3";
		this.vbox4.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w219 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator3]));
		w219.Position = 3;
		w219.Expand = false;
		w219.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.Xalign = 0F;
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\"large\"><b>Колони</b></span>");
		this.label7.UseMarkup = true;
		this.vbox4.Add (this.label7);
		global::Gtk.Box.BoxChild w220 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label7]));
		w220.Position = 4;
		w220.Expand = false;
		w220.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(10)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(20));
		// Container child table1.Gtk.Table+TableChild
		this.checkColAn = new global::Gtk.CheckButton ();
		this.checkColAn.CanFocus = true;
		this.checkColAn.Name = "checkColAn";
		this.checkColAn.Label = global::Mono.Unix.Catalog.GetString ("Анализ");
		this.checkColAn.Active = true;
		this.checkColAn.DrawIndicator = true;
		this.checkColAn.UseUnderline = true;
		this.table1.Add (this.checkColAn);
		global::Gtk.Table.TableChild w221 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColAn]));
		w221.TopAttach = ((uint)(2));
		w221.BottomAttach = ((uint)(3));
		w221.LeftAttach = ((uint)(1));
		w221.RightAttach = ((uint)(2));
		w221.XOptions = ((global::Gtk.AttachOptions)(4));
		w221.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkColDop = new global::Gtk.CheckButton ();
		this.checkColDop.CanFocus = true;
		this.checkColDop.Name = "checkColDop";
		this.checkColDop.Label = global::Mono.Unix.Catalog.GetString ("Доп.");
		this.checkColDop.Active = true;
		this.checkColDop.DrawIndicator = true;
		this.checkColDop.UseUnderline = true;
		this.table1.Add (this.checkColDop);
		global::Gtk.Table.TableChild w222 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColDop]));
		w222.TopAttach = ((uint)(1));
		w222.BottomAttach = ((uint)(2));
		w222.LeftAttach = ((uint)(7));
		w222.RightAttach = ((uint)(8));
		w222.XOptions = ((global::Gtk.AttachOptions)(4));
		w222.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkColFile = new global::Gtk.CheckButton ();
		this.checkColFile.CanFocus = true;
		this.checkColFile.Name = "checkColFile";
		this.checkColFile.Label = global::Mono.Unix.Catalog.GetString ("Файл");
		this.checkColFile.Active = true;
		this.checkColFile.DrawIndicator = true;
		this.checkColFile.UseUnderline = true;
		this.table1.Add (this.checkColFile);
		global::Gtk.Table.TableChild w223 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColFile]));
		w223.LeftAttach = ((uint)(1));
		w223.RightAttach = ((uint)(2));
		w223.XOptions = ((global::Gtk.AttachOptions)(4));
		w223.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkColMhn = new global::Gtk.CheckButton ();
		this.checkColMhn.CanFocus = true;
		this.checkColMhn.Name = "checkColMhn";
		this.checkColMhn.Label = global::Mono.Unix.Catalog.GetString ("Мех.");
		this.checkColMhn.Active = true;
		this.checkColMhn.DrawIndicator = true;
		this.checkColMhn.UseUnderline = true;
		this.table1.Add (this.checkColMhn);
		global::Gtk.Table.TableChild w224 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColMhn]));
		w224.TopAttach = ((uint)(1));
		w224.BottomAttach = ((uint)(2));
		w224.LeftAttach = ((uint)(5));
		w224.RightAttach = ((uint)(6));
		w224.XOptions = ((global::Gtk.AttachOptions)(4));
		w224.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkColMka = new global::Gtk.CheckButton ();
		this.checkColMka.CanFocus = true;
		this.checkColMka.Name = "checkColMka";
		this.checkColMka.Label = global::Mono.Unix.Catalog.GetString ("м-ка");
		this.checkColMka.Active = true;
		this.checkColMka.DrawIndicator = true;
		this.checkColMka.UseUnderline = true;
		this.table1.Add (this.checkColMka);
		global::Gtk.Table.TableChild w225 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColMka]));
		w225.LeftAttach = ((uint)(4));
		w225.RightAttach = ((uint)(5));
		w225.XOptions = ((global::Gtk.AttachOptions)(4));
		w225.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkColMtr = new global::Gtk.CheckButton ();
		this.checkColMtr.CanFocus = true;
		this.checkColMtr.Name = "checkColMtr";
		this.checkColMtr.Label = global::Mono.Unix.Catalog.GetString ("Мат.");
		this.checkColMtr.Active = true;
		this.checkColMtr.DrawIndicator = true;
		this.checkColMtr.UseUnderline = true;
		this.table1.Add (this.checkColMtr);
		global::Gtk.Table.TableChild w226 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColMtr]));
		w226.TopAttach = ((uint)(1));
		w226.BottomAttach = ((uint)(2));
		w226.LeftAttach = ((uint)(4));
		w226.RightAttach = ((uint)(5));
		w226.XOptions = ((global::Gtk.AttachOptions)(4));
		w226.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkColNvr = new global::Gtk.CheckButton ();
		this.checkColNvr.CanFocus = true;
		this.checkColNvr.Name = "checkColNvr";
		this.checkColNvr.Label = global::Mono.Unix.Catalog.GetString ("Нвр");
		this.checkColNvr.Active = true;
		this.checkColNvr.DrawIndicator = true;
		this.checkColNvr.UseUnderline = true;
		this.table1.Add (this.checkColNvr);
		global::Gtk.Table.TableChild w227 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColNvr]));
		w227.TopAttach = ((uint)(1));
		w227.BottomAttach = ((uint)(2));
		w227.LeftAttach = ((uint)(2));
		w227.RightAttach = ((uint)(3));
		w227.XOptions = ((global::Gtk.AttachOptions)(4));
		w227.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkColOpisanie = new global::Gtk.CheckButton ();
		this.checkColOpisanie.CanFocus = true;
		this.checkColOpisanie.Name = "checkColOpisanie";
		this.checkColOpisanie.Label = global::Mono.Unix.Catalog.GetString ("Описание");
		this.checkColOpisanie.Active = true;
		this.checkColOpisanie.DrawIndicator = true;
		this.checkColOpisanie.UseUnderline = true;
		this.table1.Add (this.checkColOpisanie);
		global::Gtk.Table.TableChild w228 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColOpisanie]));
		w228.LeftAttach = ((uint)(3));
		w228.RightAttach = ((uint)(4));
		w228.XOptions = ((global::Gtk.AttachOptions)(4));
		w228.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkColOsnovanie = new global::Gtk.CheckButton ();
		this.checkColOsnovanie.CanFocus = true;
		this.checkColOsnovanie.Name = "checkColOsnovanie";
		this.checkColOsnovanie.Label = global::Mono.Unix.Catalog.GetString ("Основание");
		this.checkColOsnovanie.Active = true;
		this.checkColOsnovanie.DrawIndicator = true;
		this.checkColOsnovanie.UseUnderline = true;
		this.table1.Add (this.checkColOsnovanie);
		global::Gtk.Table.TableChild w229 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColOsnovanie]));
		w229.LeftAttach = ((uint)(2));
		w229.RightAttach = ((uint)(3));
		w229.XOptions = ((global::Gtk.AttachOptions)(4));
		w229.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkColPe4 = new global::Gtk.CheckButton ();
		this.checkColPe4.CanFocus = true;
		this.checkColPe4.Name = "checkColPe4";
		this.checkColPe4.Label = global::Mono.Unix.Catalog.GetString ("Печ.");
		this.checkColPe4.Active = true;
		this.checkColPe4.DrawIndicator = true;
		this.checkColPe4.UseUnderline = true;
		this.table1.Add (this.checkColPe4);
		global::Gtk.Table.TableChild w230 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColPe4]));
		w230.TopAttach = ((uint)(1));
		w230.BottomAttach = ((uint)(2));
		w230.LeftAttach = ((uint)(8));
		w230.RightAttach = ((uint)(9));
		w230.XOptions = ((global::Gtk.AttachOptions)(4));
		w230.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkColPePr = new global::Gtk.CheckButton ();
		this.checkColPePr.CanFocus = true;
		this.checkColPePr.Name = "checkColPePr";
		this.checkColPePr.Label = global::Mono.Unix.Catalog.GetString ("Печ [%]");
		this.checkColPePr.Active = true;
		this.checkColPePr.DrawIndicator = true;
		this.checkColPePr.UseUnderline = true;
		this.table1.Add (this.checkColPePr);
		global::Gtk.Table.TableChild w231 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColPePr]));
		w231.TopAttach = ((uint)(2));
		w231.BottomAttach = ((uint)(3));
		w231.LeftAttach = ((uint)(2));
		w231.RightAttach = ((uint)(3));
		w231.XOptions = ((global::Gtk.AttachOptions)(4));
		w231.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkColSum = new global::Gtk.CheckButton ();
		this.checkColSum.CanFocus = true;
		this.checkColSum.Name = "checkColSum";
		this.checkColSum.Label = global::Mono.Unix.Catalog.GetString ("Общо");
		this.checkColSum.Active = true;
		this.checkColSum.DrawIndicator = true;
		this.checkColSum.UseUnderline = true;
		this.table1.Add (this.checkColSum);
		global::Gtk.Table.TableChild w232 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColSum]));
		w232.TopAttach = ((uint)(1));
		w232.BottomAttach = ((uint)(2));
		w232.LeftAttach = ((uint)(1));
		w232.RightAttach = ((uint)(2));
		w232.XOptions = ((global::Gtk.AttachOptions)(4));
		w232.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkColTrd = new global::Gtk.CheckButton ();
		this.checkColTrd.CanFocus = true;
		this.checkColTrd.Name = "checkColTrd";
		this.checkColTrd.Label = global::Mono.Unix.Catalog.GetString ("Труд");
		this.checkColTrd.Active = true;
		this.checkColTrd.DrawIndicator = true;
		this.checkColTrd.UseUnderline = true;
		this.table1.Add (this.checkColTrd);
		global::Gtk.Table.TableChild w233 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColTrd]));
		w233.TopAttach = ((uint)(1));
		w233.BottomAttach = ((uint)(2));
		w233.LeftAttach = ((uint)(3));
		w233.RightAttach = ((uint)(4));
		w233.XOptions = ((global::Gtk.AttachOptions)(4));
		w233.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkColUsl = new global::Gtk.CheckButton ();
		this.checkColUsl.CanFocus = true;
		this.checkColUsl.Name = "checkColUsl";
		this.checkColUsl.Label = global::Mono.Unix.Catalog.GetString ("Усл.");
		this.checkColUsl.Active = true;
		this.checkColUsl.DrawIndicator = true;
		this.checkColUsl.UseUnderline = true;
		this.table1.Add (this.checkColUsl);
		global::Gtk.Table.TableChild w234 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkColUsl]));
		w234.TopAttach = ((uint)(1));
		w234.BottomAttach = ((uint)(2));
		w234.LeftAttach = ((uint)(6));
		w234.RightAttach = ((uint)(7));
		w234.XOptions = ((global::Gtk.AttachOptions)(4));
		w234.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.Xalign = 0F;
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Системни:");
		this.table1.Add (this.label10);
		global::Gtk.Table.TableChild w235 = ((global::Gtk.Table.TableChild)(this.table1 [this.label10]));
		w235.TopAttach = ((uint)(2));
		w235.BottomAttach = ((uint)(3));
		w235.XOptions = ((global::Gtk.AttachOptions)(4));
		w235.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.Xalign = 0F;
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Основни колони:");
		this.table1.Add (this.label8);
		global::Gtk.Table.TableChild w236 = ((global::Gtk.Table.TableChild)(this.table1 [this.label8]));
		w236.XOptions = ((global::Gtk.AttachOptions)(4));
		w236.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.Xalign = 0F;
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Стойности:");
		this.table1.Add (this.label9);
		global::Gtk.Table.TableChild w237 = ((global::Gtk.Table.TableChild)(this.table1 [this.label9]));
		w237.TopAttach = ((uint)(1));
		w237.BottomAttach = ((uint)(2));
		w237.XOptions = ((global::Gtk.AttachOptions)(4));
		w237.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox4.Add (this.table1);
		global::Gtk.Box.BoxChild w238 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table1]));
		w238.Position = 5;
		w238.Expand = false;
		w238.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator4 = new global::Gtk.HSeparator ();
		this.hseparator4.Name = "hseparator4";
		this.vbox4.Add (this.hseparator4);
		global::Gtk.Box.BoxChild w239 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator4]));
		w239.Position = 6;
		w239.Expand = false;
		w239.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.Xalign = 0F;
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\"large\"><b>Други</b></span>");
		this.label13.UseMarkup = true;
		this.vbox4.Add (this.label13);
		global::Gtk.Box.BoxChild w240 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label13]));
		w240.Position = 7;
		w240.Expand = false;
		w240.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.checkbuttonFixedColumn = new global::Gtk.CheckButton ();
		this.checkbuttonFixedColumn.CanFocus = true;
		this.checkbuttonFixedColumn.Name = "checkbuttonFixedColumn";
		this.checkbuttonFixedColumn.Label = global::Mono.Unix.Catalog.GetString ("Фиксирана дължина на колоната \"Описание\"");
		this.checkbuttonFixedColumn.Active = true;
		this.checkbuttonFixedColumn.DrawIndicator = true;
		this.checkbuttonFixedColumn.UseUnderline = true;
		this.hbox8.Add (this.checkbuttonFixedColumn);
		global::Gtk.Box.BoxChild w241 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.checkbuttonFixedColumn]));
		w241.Position = 0;
		w241.Expand = false;
		this.vbox4.Add (this.hbox8);
		global::Gtk.Box.BoxChild w242 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox8]));
		w242.Position = 8;
		w242.Expand = false;
		w242.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator5 = new global::Gtk.HSeparator ();
		this.hseparator5.Name = "hseparator5";
		this.vbox4.Add (this.hseparator5);
		global::Gtk.Box.BoxChild w243 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator5]));
		w243.Position = 9;
		w243.Expand = false;
		w243.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 3;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\"large\"><b>Базова директория</b></span> <span size=\"small\">Програмата " +
			"ще събира анализите от файловете в посочената директория.</span>");
		this.label5.UseMarkup = true;
		this.vbox6.Add (this.label5);
		global::Gtk.Box.BoxChild w244 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label5]));
		w244.Position = 0;
		w244.Expand = false;
		w244.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 3;
		// Container child hbox6.Gtk.Box+BoxChild
		this.DirChoiseSettings = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Изберете базова директория"), ((global::Gtk.FileChooserAction)(2)));
		this.DirChoiseSettings.Name = "DirChoiseSettings";
		this.DirChoiseSettings.ShowHidden = true;
		this.hbox6.Add (this.DirChoiseSettings);
		global::Gtk.Box.BoxChild w245 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.DirChoiseSettings]));
		w245.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.btnRunBaseDirSettings = new global::Gtk.Button ();
		this.btnRunBaseDirSettings.CanFocus = true;
		this.btnRunBaseDirSettings.Name = "btnRunBaseDirSettings";
		this.btnRunBaseDirSettings.UseUnderline = true;
		// Container child btnRunBaseDirSettings.Gtk.Container+ContainerChild
		global::Gtk.Alignment w246 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w247 = new global::Gtk.HBox ();
		w247.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w248 = new global::Gtk.Image ();
		w248.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-directory", global::Gtk.IconSize.SmallToolbar);
		w247.Add (w248);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w250 = new global::Gtk.Label ();
		w250.LabelProp = global::Mono.Unix.Catalog.GetString (" Стартирай");
		w250.UseUnderline = true;
		w247.Add (w250);
		w246.Add (w247);
		this.btnRunBaseDirSettings.Add (w246);
		this.hbox6.Add (this.btnRunBaseDirSettings);
		global::Gtk.Box.BoxChild w254 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.btnRunBaseDirSettings]));
		w254.PackType = ((global::Gtk.PackType)(1));
		w254.Position = 1;
		w254.Expand = false;
		w254.Fill = false;
		this.vbox6.Add (this.hbox6);
		global::Gtk.Box.BoxChild w255 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox6]));
		w255.Position = 1;
		w255.Expand = false;
		w255.Fill = false;
		this.vbox4.Add (this.vbox6);
		global::Gtk.Box.BoxChild w256 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox6]));
		w256.PackType = ((global::Gtk.PackType)(1));
		w256.Position = 11;
		w256.Expand = false;
		w256.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator ();
		this.hseparator2.Name = "hseparator2";
		this.vbox4.Add (this.hseparator2);
		global::Gtk.Box.BoxChild w257 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator2]));
		w257.PackType = ((global::Gtk.PackType)(1));
		w257.Position = 12;
		w257.Expand = false;
		w257.Fill = false;
		this.notebook1.Add (this.vbox4);
		global::Gtk.Notebook.NotebookChild w258 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox4]));
		w258.Position = 4;
		// Notebook tab
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Settings");
		this.notebook1.SetTabLabel (this.vbox4, this.label14);
		this.label14.ShowAll ();
		this.Add (this.notebook1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 946;
		this.DefaultHeight = 612;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
